# Generated by Django 5.0.6 on 2024-06-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geobackend_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepthProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=100)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserInputModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_flow_rate",
                    models.FloatField(
                        help_text="The required flow rate in liters per day.",
                        verbose_name="Required Flow Rate (L/day)",
                    ),
                ),
                (
                    "hydraulic_conductivity",
                    models.FloatField(
                        help_text="The hydraulic conductivity of the aquifer in meters per day.",
                        verbose_name="Hydraulic Conductivity (m/day)",
                    ),
                ),
                (
                    "average_porosity",
                    models.FloatField(
                        help_text="The average porosity of the aquifer (0-1).",
                        verbose_name="Average Porosity",
                    ),
                ),
                (
                    "bore_lifetime_year",
                    models.FloatField(
                        help_text="The expected lifetime of the bore in years.",
                        verbose_name="Bore Lifetime (Years)",
                    ),
                ),
                (
                    "groundwater_depth",
                    models.FloatField(
                        help_text="The depth to the groundwater table in meters.",
                        verbose_name="Groundwater Depth (m)",
                    ),
                ),
                (
                    "long_term_decline_rate",
                    models.FloatField(
                        help_text="The long-term decline rate of the water level in meters per year.",
                        verbose_name="Long Term Decline Rate (m/year)",
                    ),
                ),
                (
                    "allowable_drawdown",
                    models.FloatField(
                        help_text="The allowable drawdown in meters.",
                        verbose_name="Allowable Drawdown (m)",
                    ),
                ),
                (
                    "safety_margin",
                    models.FloatField(
                        help_text="The safety margin in meters.",
                        verbose_name="Safety Margin (m)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepthLayerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aquifer_layer", models.CharField(max_length=100)),
                ("is_aquifer", models.BooleanField(blank=True, null=True)),
                ("depth_to_base", models.FloatField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="geobackend_api.depthprofilemodel",
                    ),
                ),
            ],
        ),
    ]
