# Generated by Django 5.0.6 on 2024-07-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geobackend_api", "0002_depthprofilemodel_userinputmodel_depthlayermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellBoreCalculationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("result_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="depthlayermodel",
            name="profile",
        ),
        migrations.DeleteModel(
            name="DepthQuery",
        ),
        migrations.DeleteModel(
            name="UserInputModel",
        ),
        migrations.DeleteModel(
            name="DepthLayerModel",
        ),
        migrations.DeleteModel(
            name="DepthProfileModel",
        ),
    ]
